# **Procesamiento de Lenguaje Natural**: Análisis de documentos, POS tagging y Name Entity Recognition (NER)


**Angel Navia Vázquez, Pablo Martínez Olmos**

  * 1.1 (January 2026) Revised and updated version
  

Departamento de Teoría de la Señal y Comunicaciones

**Universidad Carlos III de Madrid**

<img src='https://www.tsc.uc3m.es/~navia/figures/logo_uc3m_foot.jpg' width=400 />

In [2]:
# Ejecutamos este código para preparar el contexto.
from IPython.display import Image, display
%matplotlib inline
%config InlineBackend.figure_format = 'retina'
import matplotlib.pyplot as plt
from matplotlib import rc
from matplotlib import cm

# Configuración de las figuras matplotlib
plt.rcParams['figure.figsize'] = [8, 6]
plt.rcParams.update({'font.size': 12})

In [66]:
!pip install --upgrade spacy numpy scipy gensim nltk

Requirement already satisfied: spacy in /opt/homebrew/lib/python3.11/site-packages (3.7.5)
Collecting spacy
  Using cached spacy-3.8.11-cp311-cp311-macosx_11_0_arm64.whl.metadata (27 kB)
Requirement already satisfied: numpy in /opt/homebrew/lib/python3.11/site-packages (1.26.4)
Collecting numpy
  Using cached numpy-2.4.2-cp311-cp311-macosx_14_0_arm64.whl.metadata (6.6 kB)
Requirement already satisfied: scipy in /opt/homebrew/lib/python3.11/site-packages (1.17.1)
Requirement already satisfied: gensim in /opt/homebrew/lib/python3.11/site-packages (4.4.0)
Requirement already satisfied: nltk in /opt/homebrew/lib/python3.11/site-packages (3.9.3)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /opt/homebrew/lib/python3.11/site-packages (from spacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /opt/homebrew/lib/python3.11/site-packages (from spacy) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /opt/homebrew/lib/python3.11/site-packages (from spacy) (1.0.15)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /opt/homebrew/lib/python3.11/site-packages (from spacy) (2.0.13)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /opt/homebrew/lib/python3.11/site-packages (from spacy) (3.0.12)
Collecting thinc<8.4.0,>=8.3.4 (from spacy)
  Using cached thinc-8.3.10-cp311-cp311-macosx_11_0_arm64.whl.metadata (15 kB)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /opt/homebrew/lib/python3.11/site-packages (from spacy) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /opt/homebrew/lib/python3.11/site-packages (from spacy) (2.5.2)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /opt/homebrew/lib/python3.11/site-packages (from spacy) (2.0.10)
Requirement already satisfied: weasel<0.5.0,>=0.4.2 in /opt/homebrew/lib/python3.11/site-packages (from spacy) (0.4.3)
Requirement already satisfied: typer-slim<1.0.0,>=0.3.0 in /opt/homebrew/lib/python3.11/site-packages (from spacy) (0.23.0)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /opt/homebrew/lib/python3.11/site-packages (from spacy) (4.67.3)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /opt/homebrew/lib/python3.11/site-packages (from spacy) (2.32.5)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in /opt/homebrew/lib/python3.11/site-packages (from spacy) (2.12.5)
Requirement already satisfied: jinja2 in /opt/homebrew/lib/python3.11/site-packages (from spacy) (3.1.6)
Requirement already satisfied: setuptools in /opt/homebrew/lib/python3.11/site-packages (from spacy) (82.0.0)
Requirement already satisfied: packaging>=20.0 in /opt/homebrew/lib/python3.11/site-packages (from spacy) (26.0)
Requirement already satisfied: annotated-types>=0.6.0 in /opt/homebrew/lib/python3.11/site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in /opt/homebrew/lib/python3.11/site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (2.41.5)
Requirement already satisfied: typing-extensions>=4.14.1 in /opt/homebrew/lib/python3.11/site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /opt/homebrew/lib/python3.11/site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/homebrew/lib/python3.11/site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /opt/homebrew/lib/python3.11/site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/homebrew/lib/python3.11/site-packages (from requests<3.0.0,>=2.13.0->spacy) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in /opt/homebrew/lib/python3.11/site-packages (from requests<3.0.0,>=2.13.0->spacy) (2026.1.4)
Collecting blis<1.4.0,>=1.3.0 (from thinc<8.4.0,>=8.3.4->spacy)
  Using cached blis-1.3.3-cp311-cp311-macosx_11_0_arm64.whl.metadata (7.5 kB)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in /opt/homebrew/lib/python3.11/site-packages (from thinc<8.4.0,>=8.3.4->spacy) (0.1.5)
Requirement already satisfied: typer>=0.23.0 in /opt/homebrew/lib/python3.11/site-packages (from typer-slim<1.0.0,>=0.3.0->spacy) (0.23.0)
Requirement already satisfied: cloudpathlib<1.0.0,>=0.7.0 in /opt/homebrew/lib/python3.11/site-packages (from weasel<0.5.0,>=0.4.2->spacy) (0.23.0)
Requirement already satisfied: smart-open<8.0.0,>=5.2.1 in /opt/homebrew/lib/python3.11/site-packages (from weasel<0.5.0,>=0.4.2->spacy) (7.5.0)
Requirement already satisfied: wrapt in /opt/homebrew/lib/python3.11/site-packages (from smart-open<8.0.0,>=5.2.1->weasel<0.5.0,>=0.4.2->spacy) (2.1.1)
Requirement already satisfied: click in /opt/homebrew/lib/python3.11/site-packages (from nltk) (8.3.1)
Requirement already satisfied: joblib in /opt/homebrew/lib/python3.11/site-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /opt/homebrew/lib/python3.11/site-packages (from nltk) (2026.1.15)
Requirement already satisfied: shellingham>=1.3.0 in /opt/homebrew/lib/python3.11/site-packages (from typer>=0.23.0->typer-slim<1.0.0,>=0.3.0->spacy) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in /opt/homebrew/lib/python3.11/site-packages (from typer>=0.23.0->typer-slim<1.0.0,>=0.3.0->spacy) (14.3.2)
Requirement already satisfied: annotated-doc>=0.0.2 in /opt/homebrew/lib/python3.11/site-packages (from typer>=0.23.0->typer-slim<1.0.0,>=0.3.0->spacy) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /opt/homebrew/lib/python3.11/site-packages (from rich>=10.11.0->typer>=0.23.0->typer-slim<1.0.0,>=0.3.0->spacy) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /opt/homebrew/lib/python3.11/site-packages (from rich>=10.11.0->typer>=0.23.0->typer-slim<1.0.0,>=0.3.0->spacy) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /opt/homebrew/lib/python3.11/site-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer>=0.23.0->typer-slim<1.0.0,>=0.3.0->spacy) (0.1.2)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/homebrew/lib/python3.11/site-packages (from jinja2->spacy) (3.0.3)
Using cached spacy-3.8.11-cp311-cp311-macosx_11_0_arm64.whl (6.1 MB)
Using cached thinc-8.3.10-cp311-cp311-macosx_11_0_arm64.whl (770 kB)
Using cached numpy-2.4.2-cp311-cp311-macosx_14_0_arm64.whl (5.5 MB)
Using cached blis-1.3.3-cp311-cp311-macosx_11_0_arm64.whl (1.2 MB)
Installing collected packages: numpy, blis, thinc, spacy
  Attempting uninstall: numpy
    Found existing installation: numpy 1.26.4
    Uninstalling numpy-1.26.4:━━━━━━━━━━━━━━━━━━ 0/4 [numpy]
      Successfully uninstalled numpy-1.26.4━ 0/4 [numpy]
  Attempting uninstall: blis━━━━━━━━━━━━━━━━━━━━ 0/4 [numpy]
    Found existing installation: blis 0.7.11 0/4 [numpy]
    Uninstalling blis-0.7.11:━━━━━━━━━━━━━━━ 0/4 [numpy]
      Successfully uninstalled blis-0.7.11━━ 0/4 [numpy]
  Attempting uninstall: thinc━━━━━━━━━━━━━━━ 0/4 [numpy]
    Found existing installation: thinc 8.2.590m━━━━━━━━━━━━━━━━━━━ 2/4 [thinc]
    Uninstalling thinc-8.2.5:[90m╺━━━━━━━━━━━━━━━━━━━ 2/4 [thinc]
      Successfully uninstalled thinc-8.2.5m━━━━━━━━━━━━━━━━━━━ 2/4 [thinc]
  Attempting uninstall: spacy[0m╺━━━━━━━━━━━━━━━━━━━ 2/4 [thinc]
    Found existing installation: spacy 3.7.5━━━━━━━━━━━━━━━━━━ 2/4 [thinc]
    Uninstalling spacy-3.7.5:━━━━━━━━━╺━━━━━━━━━ 3/4 [spacy]
      Successfully uninstalled spacy-3.7.5╺━━━━━━━━━ 3/4 [spacy]
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4/4 [spacy]32m3/4 [spacy]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow 2.16.2 requires numpy<2.0.0,>=1.23.5; python_version <= "3.11", but you have numpy 2.4.2 which is incompatible.
en-core-web-md 3.7.1 requires spacy<3.8.0,>=3.7.2, but you have spacy 3.8.11 which is incompatible.
en-core-web-lg 3.7.1 requires spacy<3.8.0,>=3.7.2, but you have spacy 3.8.11 which is incompatible.
en-core-web-trf 3.7.3 requires spacy<3.8.0,>=3.7.2, but you have spacy 3.8.11 which is incompatible.
Successfully installed blis-1.3.3 numpy-2.4.2 spacy-3.8.11 thinc-8.3.10

In [3]:
%%bash
set -e

# Crear entorno nuevo con Python 3.11
python3.11 -m venv nlp_env_2026

# Activar entorno
source nlp_env_2026/bin/activate

# Actualizar herramientas
python -m pip install --upgrade pip setuptools wheel

# Instalar stack 2026
pip install \
numpy==2.4.2 \
scipy==1.17.0 \
pandas==3.0.0 \
spacy==3.8.11 \
gensim==4.4.0 \
nltk==3.9.2 \
matplotlib \
ipython \
jupyter \
ipykernel

# Descargar modelo spaCy
python -m spacy download en_core_web_md

# Registrar kernel para Jupyter
python -m ipykernel install --user --name nlp_env_2026 --display-name "Python (NLP 2026)"

echo "✅ Entorno listo. Cambia el kernel a: Python (NLP 2026)"

Requirement already satisfied: pip in ./nlp_env_2026/lib/python3.11/site-packages (26.0.1)
Requirement already satisfied: setuptools in ./nlp_env_2026/lib/python3.11/site-packages (82.0.0)
Requirement already satisfied: wheel in ./nlp_env_2026/lib/python3.11/site-packages (0.46.3)
Requirement already satisfied: packaging>=24.0 in ./nlp_env_2026/lib/python3.11/site-packages (from wheel) (26.0)
Requirement already satisfied: numpy==2.4.2 in ./nlp_env_2026/lib/python3.11/site-packages (2.4.2)
Requirement already satisfied: scipy==1.17.0 in ./nlp_env_2026/lib/python3.11/site-packages (1.17.0)
Requirement already satisfied: pandas==3.0.0 in ./nlp_env_2026/lib/python3.11/site-packages (3.0.0)
Requirement already satisfied: spacy==3.8.11 in ./nlp_env_2026/lib/python3.11/site-packages (3.8.11)
Requirement already satisfied: gensim==4.4.0 in ./nlp_env_2026/lib/python3.11/site-packages (4.4.0)
Requirement already satisfied: nltk==3.9.2 in ./nlp_env_2026/lib/python3.11/site-packages (3.9.2)
Requirement already satisfied: matplotlib in ./nlp_env_2026/lib/python3.11/site-packages (3.10.8)
Requirement already satisfied: ipython in ./nlp_env_2026/lib/python3.11/site-packages (9.10.0)
Collecting jupyter
  Downloading jupyter-1.1.1-py2.py3-none-any.whl.metadata (2.0 kB)
Requirement already satisfied: ipykernel in ./nlp_env_2026/lib/python3.11/site-packages (7.2.0)
Requirement already satisfied: python-dateutil>=2.8.2 in ./nlp_env_2026/lib/python3.11/site-packages (from pandas==3.0.0) (2.9.0.post0)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in ./nlp_env_2026/lib/python3.11/site-packages (from spacy==3.8.11) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in ./nlp_env_2026/lib/python3.11/site-packages (from spacy==3.8.11) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in ./nlp_env_2026/lib/python3.11/site-packages (from spacy==3.8.11) (1.0.15)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in ./nlp_env_2026/lib/python3.11/site-packages (from spacy==3.8.11) (2.0.13)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in ./nlp_env_2026/lib/python3.11/site-packages (from spacy==3.8.11) (3.0.12)
Requirement already satisfied: thinc<8.4.0,>=8.3.4 in ./nlp_env_2026/lib/python3.11/site-packages (from spacy==3.8.11) (8.3.10)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in ./nlp_env_2026/lib/python3.11/site-packages (from spacy==3.8.11) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in ./nlp_env_2026/lib/python3.11/site-packages (from spacy==3.8.11) (2.5.2)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in ./nlp_env_2026/lib/python3.11/site-packages (from spacy==3.8.11) (2.0.10)
Requirement already satisfied: weasel<0.5.0,>=0.4.2 in ./nlp_env_2026/lib/python3.11/site-packages (from spacy==3.8.11) (0.4.3)
Requirement already satisfied: typer-slim<1.0.0,>=0.3.0 in ./nlp_env_2026/lib/python3.11/site-packages (from spacy==3.8.11) (0.24.0)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in ./nlp_env_2026/lib/python3.11/site-packages (from spacy==3.8.11) (4.67.3)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in ./nlp_env_2026/lib/python3.11/site-packages (from spacy==3.8.11) (2.32.5)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in ./nlp_env_2026/lib/python3.11/site-packages (from spacy==3.8.11) (2.12.5)
Requirement already satisfied: jinja2 in ./nlp_env_2026/lib/python3.11/site-packages (from spacy==3.8.11) (3.1.6)
Requirement already satisfied: setuptools in ./nlp_env_2026/lib/python3.11/site-packages (from spacy==3.8.11) (82.0.0)
Requirement already satisfied: packaging>=20.0 in ./nlp_env_2026/lib/python3.11/site-packages (from spacy==3.8.11) (26.0)
Requirement already satisfied: smart_open>=1.8.1 in ./nlp_env_2026/lib/python3.11/site-packages (from gensim==4.4.0) (7.5.1)
Requirement already satisfied: click in ./nlp_env_2026/lib/python3.11/site-packages (from nltk==3.9.2) (8.3.1)
Requirement already satisfied: joblib in ./nlp_env_2026/lib/python3.11/site-packages (from nltk==3.9.2) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in ./nlp_env_2026/lib/python3.11/site-packages (from nltk==3.9.2) (2026.2.28)
Requirement already satisfied: annotated-types>=0.6.0 in ./nlp_env_2026/lib/python3.11/site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy==3.8.11) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in ./nlp_env_2026/lib/python3.11/site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy==3.8.11) (2.41.5)
Requirement already satisfied: typing-extensions>=4.14.1 in ./nlp_env_2026/lib/python3.11/site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy==3.8.11) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in ./nlp_env_2026/lib/python3.11/site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy==3.8.11) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in ./nlp_env_2026/lib/python3.11/site-packages (from requests<3.0.0,>=2.13.0->spacy==3.8.11) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in ./nlp_env_2026/lib/python3.11/site-packages (from requests<3.0.0,>=2.13.0->spacy==3.8.11) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./nlp_env_2026/lib/python3.11/site-packages (from requests<3.0.0,>=2.13.0->spacy==3.8.11) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in ./nlp_env_2026/lib/python3.11/site-packages (from requests<3.0.0,>=2.13.0->spacy==3.8.11) (2026.2.25)
Requirement already satisfied: blis<1.4.0,>=1.3.0 in ./nlp_env_2026/lib/python3.11/site-packages (from thinc<8.4.0,>=8.3.4->spacy==3.8.11) (1.3.3)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in ./nlp_env_2026/lib/python3.11/site-packages (from thinc<8.4.0,>=8.3.4->spacy==3.8.11) (0.1.5)
Requirement already satisfied: typer>=0.24.0 in ./nlp_env_2026/lib/python3.11/site-packages (from typer-slim<1.0.0,>=0.3.0->spacy==3.8.11) (0.24.1)
Requirement already satisfied: cloudpathlib<1.0.0,>=0.7.0 in ./nlp_env_2026/lib/python3.11/site-packages (from weasel<0.5.0,>=0.4.2->spacy==3.8.11) (0.23.0)
Requirement already satisfied: wrapt in ./nlp_env_2026/lib/python3.11/site-packages (from smart_open>=1.8.1->gensim==4.4.0) (2.1.1)
Requirement already satisfied: contourpy>=1.0.1 in ./nlp_env_2026/lib/python3.11/site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in ./nlp_env_2026/lib/python3.11/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in ./nlp_env_2026/lib/python3.11/site-packages (from matplotlib) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in ./nlp_env_2026/lib/python3.11/site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: pillow>=8 in ./nlp_env_2026/lib/python3.11/site-packages (from matplotlib) (12.1.1)
Requirement already satisfied: pyparsing>=3 in ./nlp_env_2026/lib/python3.11/site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: decorator>=4.3.2 in ./nlp_env_2026/lib/python3.11/site-packages (from ipython) (5.2.1)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in ./nlp_env_2026/lib/python3.11/site-packages (from ipython) (1.1.1)
Requirement already satisfied: jedi>=0.18.1 in ./nlp_env_2026/lib/python3.11/site-packages (from ipython) (0.19.2)
Requirement already satisfied: matplotlib-inline>=0.1.5 in ./nlp_env_2026/lib/python3.11/site-packages (from ipython) (0.2.1)
Requirement already satisfied: pexpect>4.3 in ./nlp_env_2026/lib/python3.11/site-packages (from ipython) (4.9.0)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in ./nlp_env_2026/lib/python3.11/site-packages (from ipython) (3.0.52)
Requirement already satisfied: pygments>=2.11.0 in ./nlp_env_2026/lib/python3.11/site-packages (from ipython) (2.19.2)
Requirement already satisfied: stack_data>=0.6.0 in ./nlp_env_2026/lib/python3.11/site-packages (from ipython) (0.6.3)
Requirement already satisfied: traitlets>=5.13.0 in ./nlp_env_2026/lib/python3.11/site-packages (from ipython) (5.14.3)
Requirement already satisfied: wcwidth in ./nlp_env_2026/lib/python3.11/site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython) (0.6.0)
Collecting notebook (from jupyter)
  Downloading notebook-7.5.4-py3-none-any.whl.metadata (10 kB)
Collecting jupyter-console (from jupyter)
  Downloading jupyter_console-6.6.3-py3-none-any.whl.metadata (5.8 kB)
Collecting nbconvert (from jupyter)
  Downloading nbconvert-7.17.0-py3-none-any.whl.metadata (8.4 kB)
Collecting ipywidgets (from jupyter)
  Downloading ipywidgets-8.1.8-py3-none-any.whl.metadata (2.4 kB)
Collecting jupyterlab (from jupyter)
  Downloading jupyterlab-4.5.5-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: appnope>=0.1.2 in ./nlp_env_2026/lib/python3.11/site-packages (from ipykernel) (0.1.4)
Requirement already satisfied: comm>=0.1.1 in ./nlp_env_2026/lib/python3.11/site-packages (from ipykernel) (0.2.3)
Requirement already satisfied: debugpy>=1.6.5 in ./nlp_env_2026/lib/python3.11/site-packages (from ipykernel) (1.8.20)
Requirement already satisfied: jupyter-client>=8.8.0 in ./nlp_env_2026/lib/python3.11/site-packages (from ipykernel) (8.8.0)
Requirement already satisfied: jupyter-core!=6.0.*,>=5.1 in ./nlp_env_2026/lib/python3.11/site-packages (from ipykernel) (5.9.1)
Requirement already satisfied: nest-asyncio>=1.4 in ./nlp_env_2026/lib/python3.11/site-packages (from ipykernel) (1.6.0)
Requirement already satisfied: psutil>=5.7 in ./nlp_env_2026/lib/python3.11/site-packages (from ipykernel) (7.2.2)
Requirement already satisfied: pyzmq>=25 in ./nlp_env_2026/lib/python3.11/site-packages (from ipykernel) (27.1.0)
Requirement already satisfied: tornado>=6.4.1 in ./nlp_env_2026/lib/python3.11/site-packages (from ipykernel) (6.5.4)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in ./nlp_env_2026/lib/python3.11/site-packages (from jedi>=0.18.1->ipython) (0.8.6)
Requirement already satisfied: platformdirs>=2.5 in ./nlp_env_2026/lib/python3.11/site-packages (from jupyter-core!=6.0.*,>=5.1->ipykernel) (4.9.2)
Requirement already satisfied: ptyprocess>=0.5 in ./nlp_env_2026/lib/python3.11/site-packages (from pexpect>4.3->ipython) (0.7.0)
Requirement already satisfied: six>=1.5 in ./nlp_env_2026/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas==3.0.0) (1.17.0)
Requirement already satisfied: executing>=1.2.0 in ./nlp_env_2026/lib/python3.11/site-packages (from stack_data>=0.6.0->ipython) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in ./nlp_env_2026/lib/python3.11/site-packages (from stack_data>=0.6.0->ipython) (3.0.1)
Requirement already satisfied: pure-eval in ./nlp_env_2026/lib/python3.11/site-packages (from stack_data>=0.6.0->ipython) (0.2.3)
Requirement already satisfied: shellingham>=1.3.0 in ./nlp_env_2026/lib/python3.11/site-packages (from typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy==3.8.11) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in ./nlp_env_2026/lib/python3.11/site-packages (from typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy==3.8.11) (14.3.3)
Requirement already satisfied: annotated-doc>=0.0.2 in ./nlp_env_2026/lib/python3.11/site-packages (from typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy==3.8.11) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in ./nlp_env_2026/lib/python3.11/site-packages (from rich>=12.3.0->typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy==3.8.11) (4.0.0)
Requirement already satisfied: mdurl~=0.1 in ./nlp_env_2026/lib/python3.11/site-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy==3.8.11) (0.1.2)
Collecting widgetsnbextension~=4.0.14 (from ipywidgets->jupyter)
  Downloading widgetsnbextension-4.0.15-py3-none-any.whl.metadata (1.6 kB)
Collecting jupyterlab_widgets~=3.0.15 (from ipywidgets->jupyter)
  Downloading jupyterlab_widgets-3.0.16-py3-none-any.whl.metadata (20 kB)
Requirement already satisfied: MarkupSafe>=2.0 in ./nlp_env_2026/lib/python3.11/site-packages (from jinja2->spacy==3.8.11) (3.0.3)
Collecting async-lru>=1.0.0 (from jupyterlab->jupyter)
  Downloading async_lru-2.2.0-py3-none-any.whl.metadata (7.2 kB)
Collecting httpx<1,>=0.25.0 (from jupyterlab->jupyter)
  Using cached httpx-0.28.1-py3-none-any.whl.metadata (7.1 kB)
Collecting jupyter-lsp>=2.0.0 (from jupyterlab->jupyter)
  Downloading jupyter_lsp-2.3.0-py3-none-any.whl.metadata (1.8 kB)
Collecting jupyter-server<3,>=2.4.0 (from jupyterlab->jupyter)
  Downloading jupyter_server-2.17.0-py3-none-any.whl.metadata (8.5 kB)
Collecting jupyterlab-server<3,>=2.28.0 (from jupyterlab->jupyter)
  Downloading jupyterlab_server-2.28.0-py3-none-any.whl.metadata (5.9 kB)
Collecting notebook-shim>=0.2 (from jupyterlab->jupyter)
  Downloading notebook_shim-0.2.4-py3-none-any.whl.metadata (4.0 kB)
Collecting anyio (from httpx<1,>=0.25.0->jupyterlab->jupyter)
  Using cached anyio-4.12.1-py3-none-any.whl.metadata (4.3 kB)
Collecting httpcore==1.* (from httpx<1,>=0.25.0->jupyterlab->jupyter)
  Using cached httpcore-1.0.9-py3-none-any.whl.metadata (21 kB)
Collecting h11>=0.16 (from httpcore==1.*->httpx<1,>=0.25.0->jupyterlab->jupyter)
  Using cached h11-0.16.0-py3-none-any.whl.metadata (8.3 kB)
Collecting argon2-cffi>=21.1 (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Downloading argon2_cffi-25.1.0-py3-none-any.whl.metadata (4.1 kB)
Collecting jupyter-events>=0.11.0 (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Downloading jupyter_events-0.12.0-py3-none-any.whl.metadata (5.8 kB)
Collecting jupyter-server-terminals>=0.4.4 (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Downloading jupyter_server_terminals-0.5.4-py3-none-any.whl.metadata (5.9 kB)
Collecting nbformat>=5.3.0 (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Downloading nbformat-5.10.4-py3-none-any.whl.metadata (3.6 kB)
Collecting overrides>=5.0 (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Downloading overrides-7.7.0-py3-none-any.whl.metadata (5.8 kB)
Collecting prometheus-client>=0.9 (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Downloading prometheus_client-0.24.1-py3-none-any.whl.metadata (2.1 kB)
Collecting send2trash>=1.8.2 (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Downloading send2trash-2.1.0-py3-none-any.whl.metadata (4.1 kB)
Collecting terminado>=0.8.3 (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Downloading terminado-0.18.1-py3-none-any.whl.metadata (5.8 kB)
Collecting websocket-client>=1.7 (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Downloading websocket_client-1.9.0-py3-none-any.whl.metadata (8.3 kB)
Collecting babel>=2.10 (from jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter)
  Downloading babel-2.18.0-py3-none-any.whl.metadata (2.2 kB)
Collecting json5>=0.9.0 (from jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter)
  Downloading json5-0.13.0-py3-none-any.whl.metadata (36 kB)
Collecting jsonschema>=4.18.0 (from jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter)
  Downloading jsonschema-4.26.0-py3-none-any.whl.metadata (7.6 kB)
Collecting argon2-cffi-bindings (from argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Downloading argon2_cffi_bindings-25.1.0-cp39-abi3-macosx_11_0_arm64.whl.metadata (7.4 kB)
Collecting attrs>=22.2.0 (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter)
  Using cached attrs-25.4.0-py3-none-any.whl.metadata (10 kB)
Collecting jsonschema-specifications>=2023.03.6 (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter)
  Downloading jsonschema_specifications-2025.9.1-py3-none-any.whl.metadata (2.9 kB)
Collecting referencing>=0.28.4 (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter)
  Downloading referencing-0.37.0-py3-none-any.whl.metadata (2.8 kB)
Collecting rpds-py>=0.25.0 (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter)
  Downloading rpds_py-0.30.0-cp311-cp311-macosx_11_0_arm64.whl.metadata (4.1 kB)
Collecting python-json-logger>=2.0.4 (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Downloading python_json_logger-4.0.0-py3-none-any.whl.metadata (4.0 kB)
Collecting pyyaml>=5.3 (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Using cached pyyaml-6.0.3-cp311-cp311-macosx_11_0_arm64.whl.metadata (2.4 kB)
Collecting rfc3339-validator (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Downloading rfc3339_validator-0.1.4-py2.py3-none-any.whl.metadata (1.5 kB)
Collecting rfc3986-validator>=0.1.1 (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Downloading rfc3986_validator-0.1.1-py2.py3-none-any.whl.metadata (1.7 kB)
Collecting fqdn (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Downloading fqdn-1.5.1-py3-none-any.whl.metadata (1.4 kB)
Collecting isoduration (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Downloading isoduration-20.11.0-py3-none-any.whl.metadata (5.7 kB)
Collecting jsonpointer>1.13 (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Downloading jsonpointer-3.0.0-py2.py3-none-any.whl.metadata (2.3 kB)
Collecting rfc3987-syntax>=1.1.0 (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Downloading rfc3987_syntax-1.1.0-py3-none-any.whl.metadata (7.7 kB)
Collecting uri-template (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Downloading uri_template-1.3.0-py3-none-any.whl.metadata (8.8 kB)
Collecting webcolors>=24.6.0 (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Downloading webcolors-25.10.0-py3-none-any.whl.metadata (2.2 kB)
Collecting beautifulsoup4 (from nbconvert->jupyter)
  Downloading beautifulsoup4-4.14.3-py3-none-any.whl.metadata (3.8 kB)
Collecting bleach!=5.0.0 (from bleach[css]!=5.0.0->nbconvert->jupyter)
  Downloading bleach-6.3.0-py3-none-any.whl.metadata (31 kB)
Collecting defusedxml (from nbconvert->jupyter)
  Downloading defusedxml-0.7.1-py2.py3-none-any.whl.metadata (32 kB)
Collecting jupyterlab-pygments (from nbconvert->jupyter)
  Downloading jupyterlab_pygments-0.3.0-py3-none-any.whl.metadata (4.4 kB)
Collecting mistune<4,>=2.0.3 (from nbconvert->jupyter)
  Downloading mistune-3.2.0-py3-none-any.whl.metadata (1.9 kB)
Collecting nbclient>=0.5.0 (from nbconvert->jupyter)
  Downloading nbclient-0.10.4-py3-none-any.whl.metadata (8.3 kB)
Collecting pandocfilters>=1.4.1 (from nbconvert->jupyter)
  Downloading pandocfilters-1.5.1-py2.py3-none-any.whl.metadata (9.0 kB)
Collecting webencodings (from bleach!=5.0.0->bleach[css]!=5.0.0->nbconvert->jupyter)
  Downloading webencodings-0.5.1-py2.py3-none-any.whl.metadata (2.1 kB)
Collecting tinycss2<1.5,>=1.1.0 (from bleach[css]!=5.0.0->nbconvert->jupyter)
  Downloading tinycss2-1.4.0-py3-none-any.whl.metadata (3.0 kB)
Collecting fastjsonschema>=2.15 (from nbformat>=5.3.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Downloading fastjsonschema-2.21.2-py3-none-any.whl.metadata (2.3 kB)
Collecting lark>=1.2.2 (from rfc3987-syntax>=1.1.0->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Downloading lark-1.3.1-py3-none-any.whl.metadata (1.8 kB)
Collecting cffi>=1.0.1 (from argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Downloading cffi-2.0.0-cp311-cp311-macosx_11_0_arm64.whl.metadata (2.6 kB)
Collecting pycparser (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Downloading pycparser-3.0-py3-none-any.whl.metadata (8.2 kB)
Collecting soupsieve>=1.6.1 (from beautifulsoup4->nbconvert->jupyter)
  Downloading soupsieve-2.8.3-py3-none-any.whl.metadata (4.6 kB)

In [3]:
import numpy as np
import scipy
import pandas as pd
import spacy
import gensim
import nltk

print(f"NumPy version: {np.__version__}")
print(f"Scipy version: {scipy.__version__}")
print(f"Pandas version: {pd.__version__}")
print(f"Spacy version: {spacy.__version__}")
print(f"Gensim version: {gensim.__version__}")
print(f"NLTK version: {nltk.__version__}")

# 2025
# NumPy version: 1.26.4
# Scipy version: 1.13.1
# Pandas version: 2.2.3
# Spacy version: 3.8.4
# Gensim version: 4.3.3
# NLTK version: 3.9.1

# 2026
# NumPy version: 2.4.2
# Scipy version: 1.17.0
# Pandas version: 3.0.0
# Spacy version: 3.8.11
# Gensim version: 4.4.0
# NLTK version: 3.9.2

NumPy version: 2.4.2
Scipy version: 1.17.0
Pandas version: 3.0.0
Spacy version: 3.8.11
Gensim version: 4.4.0
NLTK version: 3.9.2

# 1 - Técnicas de análisis de texto

En la sesión de hoy aprenderemos distintas técnicas relevantes para **analizar la estructura de un texto** que pueden ser útiles para la extracción de características del mismo. Recordemos que hasta ahora hemos aprendido las siguientes técnicas de extracción de características:

- **Vectorización** de un documento con un **BoW**.
- **Vectorización** de un documento con **TF-IDF**.
- **Extracción de frases clave** de un documento con **LSA** y **TextRank**.
- **Extracción de palabras clave** con **N-grams** (collocations) y **RAKE**.

En todas las técnicas anteriores, **no hemos tenido en cuenta ni el tipo de palabras utilizadas ni la estructura ni la sintaxis del texto**. En la sesión de hoy, presentaremos las siguientes técnicas que sí tienen en cuenta estos aspectos:

- **Part of Speech (POS) Tagging**
- Análisis superficial (**Shallow parsing**)
- Detección de entidades (**Name entity recognition, NER**)
- Análisis de dependencias (**Dependency Parsing**)

# 2 - Part of Speech (POS) Tagging

El objetivo es asignar a cada palabra de un determinado texto una etiqueta  específica (**categoría léxica**) en función de su **contexto sintáctico y su función**.  Este etiquetado es realmente útil en NLP para obtener características específicas de un texto. Por ejemplo, podemos filtrar los sustantivos y determinar los más destacados.

En idioma inglés, utilizaremos la notación [**Penn Treebank**](https://repository.upenn.edu/cgi/viewcontent.cgi?article=1603&context=cis_reports) para el etiquetado. En este [enlace](https://repository.upenn.edu/cgi/viewcontent.cgi?article=1603&context=cis_reports) puede encontrarse una descripción detallada de cada categoría, con ejemplos.

<center>
<img src="http://www.tsc.uc3m.es/~navia/figures/tags.png" width="40%">
</center>

Un aspecto común a cualquier algoritmo de POS tagging es la construcción de un método para **estimar la etiqueta $y_i$ o categoría**  asociada a la palabra i-ésima $\mathbf{x}_i$ dadas las palabras anteriores $\mathbf{x}_j$ para $j < i$ o incluso las posteriores dentro de una ventana de procesado. Ejemplos clásicos de métodos para POS tagging son los **Modelos Ocultos de Markov, (ing. "Hidden Markov Models", HMMs)** y **Conditional Random Fields, CRFs**. No entraremos en mayor detalle en el funcionamiento de estos modelos, disponéis de más información en este [capítulo de libro](https://web.stanford.edu/~jurafsky/slp3/8.pdf).

<center>
<img src="http://www.tsc.uc3m.es/~navia/figures/HMM_slide.001.jpeg" width="70%">
</center>

En la actualidad, **los métodos con mayor precisión** se basan en [redes **neuronales recurrentes (RNNs)**](https://arxiv.org/abs/1510.06168) o de tipo [**transformer**](https://github.com/soutsios/pos-tagger-bert). Estos modelos de procesado de lenguaje se utilizan también en los "**Large Language Models**" (**LLMs**), fundamento de los esquemas de **Inteligencia Artificial** (**IA**) más recientes, y los revisaremos con mayor detalle más adelante.  

<center>
<img src="http://www.tsc.uc3m.es/~navia/figures/rnnPOS.png" width="50%">
</center>

### 2.1 - POS tagging usando spaCy

In [4]:
# Descargamos el modelo Spacy
!python -m spacy download en_core_web_md

Collecting en-core-web-md==3.8.0
  Using cached https://github.com/explosion/spacy-models/releases/download/en_core_web_md-3.8.0/en_core_web_md-3.8.0-py3-none-any.whl (33.5 MB)
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_md')

In [5]:
# Analizamos una frase con Spacy

nlp = spacy.load("en_core_web_md")

sentence = 'I am an engineer. Some day I hope to engineer an electric engine. John builds a circuit.'

doc_spacy = nlp(sentence)
print(type(doc_spacy))
print(doc_spacy)

<class 'spacy.tokens.doc.Doc'>
I am an engineer. Some day I hope to engineer an electric engine. John builds a circuit.

Recordemos que `doc` es un objeto iterable, compuesto por elementos tipo [`token`](https://spacy.io/api/token) que a su vez son objetos con propiedades en Spacy que nos permiten acceder a una serie de atributos léxicos, los principales son:

- **lemma**: lema de la palabra
- **pos**: la etiqueta POS simple ("PRON", "NOUN", "VERB", etc.)
- **tag**: la etiqueta POS detallada ("PRP", "NNP", "VBP", etc.)
- **dep**: el tipo de dependencia sintáctica ("nominal subject", "attribute", "noun phrase as adverbial modifier")

In [6]:
for token in doc_spacy:
    print(token.text, token.lemma_, token.pos_, token.tag_, token.dep_)
    print('-' * 50)

I I PRON PRP nsubj
--------------------------------------------------
am be AUX VBP ROOT
--------------------------------------------------
an an DET DT det
--------------------------------------------------
engineer engineer NOUN NN attr
--------------------------------------------------
. . PUNCT . punct
--------------------------------------------------
Some some DET DT det
--------------------------------------------------
day day NOUN NN npadvmod
--------------------------------------------------
I I PRON PRP nsubj
--------------------------------------------------
hope hope VERB VBP ROOT
--------------------------------------------------
to to PART TO aux
--------------------------------------------------
engineer engineer VERB VB xcomp
--------------------------------------------------
an an DET DT det
--------------------------------------------------
electric electric ADJ JJ amod
--------------------------------------------------
engine engine NOUN NN dobj
--------------------------------------------------
. . PUNCT . punct
--------------------------------------------------
John John PROPN NNP nsubj
--------------------------------------------------
builds build VERB VBZ ROOT
--------------------------------------------------
a a DET DT det
--------------------------------------------------
circuit circuit NOUN NN dobj
--------------------------------------------------
. . PUNCT . punct
--------------------------------------------------

### Ejercicio:

Ampliar la visualización de las etiquetas añadiendo las explicaciones de cada una de ellas ("spacy.explain"), y visualizarla usando pandas. Debería verse una tabla como esta:


<center>
<img src="http://www.tsc.uc3m.es/~navia/figures/pandas_ejercicio.png" width="80%">
</center>

### Solución:

In [7]:
spacy_pos_tagged = [(token.text, token.lemma_, token.pos_ + " (" + spacy.explain(token.pos_)+ ")", token.tag_ + " (" + spacy.explain(token.tag_)+ ")",  token.dep_+ " (" + spacy.explain(token.dep_)+ ")") for token in doc_spacy]
df = pd.DataFrame(spacy_pos_tagged, columns=['Word','Word_Lemma','POS simple', 'POS detallada', "DEP"])
left_aligned_df = df.style.set_properties(**{'text-align': 'left'})
left_aligned_df = left_aligned_df.set_table_styles([dict(selector='th', props=[('text-align', 'left')])])

display(left_aligned_df)

Fijémonos como el modelo de **POS tagging** ha sido capaz de identificar, a través del **contexto**, que la primera aparición de "engineer" se trata de un nombre, y la segunda un verbo. También es capaz de distinguir si un nombre es sujeto u objeto directo, por ejemplo.

# 3 - Shallow Parsing o Chunking (análisis sintáctico superficial o fragmentación)

El análisis sintáctico superficial o fragmentación (**shallow parsing (SP) or chunking**) es una técnica para **agrupar tokens adyacentes en "frases" en función de sus etiquetas POS**. En lo siguiente, entendemos una **"frase" como una agrupación de palabras sin significado completo, al carecer de estructura de sujeto-predicado**.

**SP** típicamente se centra en la identificación de **determinados tipos de frases**, tales como frases sustantivas o verbales. **SP no realiza un análisis profundo** de dichas frases para determinar la relación entre éstas mediante mediante reglas sintácticas o gramáticas. En esto último se centran métodos tales como **Constituency Parsing (CP)** y **Dependency Parsing (DP)**.

Hay **cinco categorías principales de frases**, que se describen a continuación:

- **Frase sustantiva** ([Noun Phrase](https://dictionary.cambridge.org/es/gramatica/gramatica-britanica/noun-phrases?q=Noun+phrases)  **NP**): Un sustantivo actúa como palabra principal. Las frases sustantivas actúan como sujeto u objeto directo que recibe la acción del verbo. Pueden ser reemplazadas por un pronombre sin hacer que la oración o cláusula sea sintácticamente incorrecta. Ej: "**`Mi mejor amigo de la infancia`** vive en Londres"; "**`Él`** vive en Londres".

- **Frase verbal** ([Verb phrase](https://dictionary.cambridge.org/es/gramatica/gramatica-britanica/verb-phrases?q=Verb+phrases)  **VP**): Tienen un verbo que actúa como palabra principal, incluyendo el verbo principal, infinitivos y participios. Este verbo puede ir seguido de otras frases o complementos. Las frases verbales son útiles para **comprender las acciones** en las que participan los sustantivos. Ej: "Los estudiantes **`están estudiando para el examen final`**."

- **Frase adjetiva** ([Adjective phrase](https://dictionary.cambridge.org/es/gramatica/gramatica-britanica/adjective-phrases)  **ADJP**): Son frases cuya palabra principal es un adjetivo. Su función principal es **describir o calificar sustantivos y pronombres** en una oración y se colocarán antes o después del sustantivo o pronombre. Ej: "Esa película fue **`increíblemente aburrida`**."

- **Frase de adverbio** ([Adverb phrase](https://dictionary.cambridge.org/es/gramatica/gramatica-britanica/adverb-phrases?q=Adverb+phrases) o **ADVP**): un adverbio actúa como la palabra principal de la frase. Las frases de adverbio se utilizan como **modificadores de sustantivos, verbos o adverbios** al proporcionar más detalles para describirlos o calificarlos. Ej: "El guepardo corre **`muy rápidamente`**."

- **Prepositional phrase** ([Prepositional phrase](https://dictionary.cambridge.org/es/gramatica/gramatica-britanica/prepositional-phrases?q=Prepositional+phrases) **PP**): Estas frases suelen contener una **preposición como palabra principal** y otros componentes léxicos como sustantivos, pronombres, etc. Actúan como un adjetivo o adverbio que describe otras palabras o frases. Ej: "Dejé las llaves **`sobre la mesa de cocina`**."

La detección de frases sustantivas (**NP chunking**) es la variante más común de SP. Vamos a ver cómo Spacy nos da una solución directa usando el objeto `doc.noun_chunks`.

In [8]:
sentence = "Artificial intelligence in the context of computer science, is a discipline and a set of cognitive and intellectual capabilities expressed by computer systems or combinations of algorithms whose purpose is the creation of machines that imitate human intelligence to perform tasks, and that can improve as they collect more and more information."

doc = nlp(sentence)

for chunk in doc.noun_chunks:
    print(chunk.text)
    print('-' * 20)

Artificial intelligence
--------------------
the context
--------------------
computer science
--------------------
a discipline
--------------------
a set
--------------------
cognitive and intellectual capabilities
--------------------
computer systems
--------------------
combinations
--------------------
algorithms
--------------------
whose purpose
--------------------
the creation
--------------------
machines
--------------------
that
--------------------
human intelligence
--------------------
tasks
--------------------
that
--------------------
they
--------------------
more and more information
--------------------

Por otro lado, Spacy **no proporciona** una solución directa para encontrar el resto de tipos de frases. Para encontrar dichas frases hay que utilizar un **matcher de expresiones, indicando explícitamente los patrones que se están buscando**. Veremos a continuación algunos ejemplos de uso de la utilidad **`matcher`** de Spacy.

Como el proceso **POS tagging** se basa en un modelo entrenado con ejemplos, **no es infalible**. En todo caso, siempre podemos refinar el proceso usando **expresiones regulares** y la clase [**Matcher**](https://spacy.io/api/matcher) de Spacy. Se pueden encontrar muchos ejemplos de uso ['aquí'](https://spacy.io/usage/rule-based-matching#matcher). Por ejemplo, nos puede interesar encontrar las frases en las que se menciona la compra de un producto o el viaje a algún país, por ejemplo.

Esta son algunos de los atributos de **matcher** que podremos a utilizar:

- **TEXT**: el texto exacto de un token.
- **LENGTH**: La longitud del texto del token.
- **IS_ALPHA, IS_ASCII, IS_DIGIT**: el texto del token consta de caracteres alfabéticos, caracteres ASCII y dígitos.
- **IS_LOWER, IS_UPPER, IS_TITLE**: el texto del token está en minúsculas, mayúsculas y título.
- **IS_PUNCT, IS_SPACE, IS_STOP**: el token es puntuación, espacios en blanco y palabra vacía.
- **IS_SENT_START**: el token es el comienzo de la oración.
- **LIKE_NUM, LIKE_URL, LIKE_EMAIL**: el texto del token se parece a un número, URL o correo electrónico.
- **POS, TAG, MORPH, DEP, LEMMA, SHAPE**: la etiqueta de parte del discurso simple y extendida del token, análisis morfológico, etiqueta de dependencia, lema, forma.
- **ENT_TYPE**: tipo de entidad NER (lo veremos a continuación).
- **REGEX**: expresión regular.

La librería **NLTK** ofrece numerosos **corpus de texto**, y una parte de ellos son **libros completos**, concretamente algunos de los disponibles en el [**Proyecto Gutenberg**](http://www.gutenberg.org), un repositorio público de libros libres y/o sin derechos de copyright en vigor.  

Veamos cómo acceder a dichos contenidos.

In [9]:
from nltk.corpus import gutenberg

In [10]:
import nltk
nltk.download('gutenberg')

[nltk_data] Downloading package gutenberg to
[nltk_data]     /Users/matveypro/nltk_data...
[nltk_data]   Package gutenberg is already up-to-date!

True

In [11]:
ids = gutenberg.fileids()
print("Estos son los {} libros disponibles:".format(len(ids)))
for id in ids:
  print(id)

Estos son los 18 libros disponibles:
austen-emma.txt
austen-persuasion.txt
austen-sense.txt
bible-kjv.txt
blake-poems.txt
bryant-stories.txt
burgess-busterbrown.txt
carroll-alice.txt
chesterton-ball.txt
chesterton-brown.txt
chesterton-thursday.txt
edgeworth-parents.txt
melville-moby_dick.txt
milton-paradise.txt
shakespeare-caesar.txt
shakespeare-hamlet.txt
shakespeare-macbeth.txt
whitman-leaves.txt

Vamos a acceder al libro de Alicia en el país de las maravillas, para su uso en este ejemplo.

In [12]:
id = "carroll-alice.txt"
book = gutenberg.raw(id)

print("El libro {} contiene {} caracteres.".format(id, len(book)))

print("\nEste es el inicio del libro:\n")
print(book[:500] + " (...)")

# A efectos del procesado de texto, vamos a eliminar los retornos:
book = book.replace('\n', ' ')

print("\nEste es el inicio del libro, sin retornos:\n")
print(book[:500] + " (...)")

El libro carroll-alice.txt contiene 144395 caracteres.

Este es el inicio del libro:

[Alice's Adventures in Wonderland by Lewis Carroll 1865]

CHAPTER I. Down the Rabbit-Hole

Alice was beginning to get very tired of sitting by her sister on the
bank, and of having nothing to do: once or twice she had peeped into the
book her sister was reading, but it had no pictures or conversations in
it, 'and what is the use of a book,' thought Alice 'without pictures or
conversation?'

So she was considering in her own mind (as well as she could, for the
hot day made her feel very sleepy an (...)

Este es el inicio del libro, sin retornos:

[Alice's Adventures in Wonderland by Lewis Carroll 1865]  CHAPTER I. Down the Rabbit-Hole  Alice was beginning to get very tired of sitting by her sister on the bank, and of having nothing to do: once or twice she had peeped into the book her sister was reading, but it had no pictures or conversations in it, 'and what is the use of a book,' thought Alice 'without pictures or conversation?'  So she was considering in her own mind (as well as she could, for the hot day made her feel very sleepy an (...)

Vamos a utilizar la herramienta "**matcher**" para encontrar **patrones específicos**. Comenzaremos por localizar verbos:

In [13]:
# Activamos el matcher y procesamos el libro con Spacy
from spacy.matcher import Matcher
book_spacy = nlp(book)

In [14]:
# Buscamos verbos en el vocabulario del libro:
patron1 = [{"POS": "VERB"}]
buscador = Matcher(nlp.vocab)
buscador.add("Patron1", [patron1])
coincidencias = buscador(book_spacy)
print(coincidencias)

[(10057817139820732965, 22, 23), (10057817139820732965, 24, 25), (10057817139820732965, 28, 29), (10057817139820732965, 38, 39), (10057817139820732965, 41, 42), (10057817139820732965, 48, 49), (10057817139820732965, 55, 56), (10057817139820732965, 59, 60), (10057817139820732965, 78, 79), (10057817139820732965, 91, 92), (10057817139820732965, 107, 108), (10057817139820732965, 109, 110), (10057817139820732965, 120, 121), (10057817139820732965, 131, 132), (10057817139820732965, 134, 135), (10057817139820732965, 146, 147), (10057817139820732965, 153, 154), (10057817139820732965, 164, 165), (10057817139820732965, 174, 175), (10057817139820732965, 177, 178), (10057817139820732965, 197, 198), (10057817139820732965, 203, 204), (10057817139820732965, 211, 212), (10057817139820732965, 221, 222), (10057817139820732965, 231, 232), (10057817139820732965, 242, 243), (10057817139820732965, 248, 249), (10057817139820732965, 252, 253), (10057817139820732965, 259, 260), (10057817139820732965, 268, 269), (10057817139820732965, 282, 283), (10057817139820732965, 288, 289), (10057817139820732965, 293, 294), (10057817139820732965, 307, 308), (10057817139820732965, 309, 310), (10057817139820732965, 325, 326), (10057817139820732965, 332, 333), (10057817139820732965, 340, 341), (10057817139820732965, 349, 350), (10057817139820732965, 361, 362), (10057817139820732965, 369, 370), (10057817139820732965, 374, 375), (10057817139820732965, 376, 377), (10057817139820732965, 380, 381), (10057817139820732965, 382, 383), (10057817139820732965, 399, 400), (10057817139820732965, 405, 406), (10057817139820732965, 411, 412), (10057817139820732965, 414, 415), (10057817139820732965, 419, 420), (10057817139820732965, 422, 423), (10057817139820732965, 424, 425), (10057817139820732965, 430, 431), (10057817139820732965, 432, 433), (10057817139820732965, 435, 436), (10057817139820732965, 440, 441), (10057817139820732965, 449, 450), (10057817139820732965, 454, 455), (10057817139820732965, 463, 464), (10057817139820732965, 467, 468), (10057817139820732965, 479, 480), (10057817139820732965, 483, 484), (10057817139820732965, 488, 489), (10057817139820732965, 499, 500), (10057817139820732965, 503, 504), (10057817139820732965, 521, 522), (10057817139820732965, 523, 524), (10057817139820732965, 529, 530), (10057817139820732965, 533, 534), (10057817139820732965, 535, 536), (10057817139820732965, 544, 545), (10057817139820732965, 553, 554), (10057817139820732965, 568, 569), (10057817139820732965, 571, 572), (10057817139820732965, 580, 581), (10057817139820732965, 590, 591), (10057817139820732965, 598, 599), (10057817139820732965, 626, 627), (10057817139820732965, 633, 634), (10057817139820732965, 639, 640), (10057817139820732965, 646, 647), (10057817139820732965, 653, 654), (10057817139820732965, 662, 663), (10057817139820732965, 664, 665), (10057817139820732965, 681, 682), (10057817139820732965, 685, 686), (10057817139820732965, 708, 709), (10057817139820732965, 715, 716), (10057817139820732965, 719, 720), (10057817139820732965, 729, 730), (10057817139820732965, 746, 747), (10057817139820732965, 753, 754), (10057817139820732965, 759, 760), (10057817139820732965, 767, 768), (10057817139820732965, 771, 772), (10057817139820732965, 778, 779), (10057817139820732965, 784, 785), (10057817139820732965, 789, 790), (10057817139820732965, 793, 794), (10057817139820732965, 803, 804), (10057817139820732965, 805, 806), (10057817139820732965, 811, 812), (10057817139820732965, 829, 830), (10057817139820732965, 841, 842), (10057817139820732965, 852, 853), (10057817139820732965, 854, 855), (10057817139820732965, 865, 866), (10057817139820732965, 882, 883), (10057817139820732965, 884, 885), (10057817139820732965, 887, 888), (10057817139820732965, 894, 895), (10057817139820732965, 901, 902), (10057817139820732965, 904, 905), (10057817139820732965, 917, 918), (10057817139820732965, 920, 921), (10057817139820732965, 927, 928), (10057817139820732965, 929, 930), (10057817139820732965, 934, 935), (10057817139820732965, 936, 937), (10057817139820732965, 949, 950), (10057817139820732965, 953, 954), (10057817139820732965, 958, 959), (10057817139820732965, 959, 960), (10057817139820732965, 964, 965), (10057817139820732965, 974, 975), (10057817139820732965, 986, 987), (10057817139820732965, 989, 990), (10057817139820732965, 1004, 1005), (10057817139820732965, 1013, 1014), (10057817139820732965, 1027, 1028), (10057817139820732965, 1040, 1041), (10057817139820732965, 1045, 1046), (10057817139820732965, 1049, 1050), (10057817139820732965, 1055, 1056), (10057817139820732965, 1057, 1058), (10057817139820732965, 1062, 1063), (10057817139820732965, 1064, 1065), (10057817139820732965, 1078, 1079), (10057817139820732965, 1083, 1084), (10057817139820732965, 1093, 1094), (10057817139820732965, 1100, 1101), (10057817139820732965, 1106, 1107), (10057817139820732965, 1114, 1115), (10057817139820732965, 1118, 1119), (10057817139820732965, 1122, 1123), (10057817139820732965, 1126, 1127), (10057817139820732965, 1132, 1133), (10057817139820732965, 1134, 1135), (10057817139820732965, 1138, 1139), (10057817139820732965, 1146, 1147), (10057817139820732965, 1157, 1158), (10057817139820732965, 1165, 1166), (10057817139820732965, 1179, 1180), (10057817139820732965, 1201, 1202), (10057817139820732965, 1205, 1206), (10057817139820732965, 1216, 1217), (10057817139820732965, 1242, 1243), (10057817139820732965, 1247, 1248), (10057817139820732965, 1253, 1254), (10057817139820732965, 1256, 1257), (10057817139820732965, 1268, 1269), (10057817139820732965, 1270, 1271), (10057817139820732965, 1274, 1275), (10057817139820732965, 1289, 1290), (10057817139820732965, 1299, 1300), (10057817139820732965, 1311, 1312), (10057817139820732965, 1314, 1315), (10057817139820732965, 1325, 1326), (10057817139820732965, 1332, 1333), (10057817139820732965, 1339, 1340), (10057817139820732965, 1350, 1351), (10057817139820732965, 1368, 1369), (10057817139820732965, 1373, 1374), (10057817139820732965, 1379, 1380), (10057817139820732965, 1385, 1386), (10057817139820732965, 1392, 1393), (10057817139820732965, 1402, 1403), (10057817139820732965, 1408, 1409), (10057817139820732965, 1427, 1428), (10057817139820732965, 1462, 1463), (10057817139820732965, 1476, 1477), (10057817139820732965, 1484, 1485), (10057817139820732965, 1500, 1501), (10057817139820732965, 1515, 1516), (10057817139820732965, 1519, 1520), (10057817139820732965, 1523, 1524), (10057817139820732965, 1526, 1527), (10057817139820732965, 1542, 1543), (10057817139820732965, 1545, 1546), (10057817139820732965, 1555, 1556), (10057817139820732965, 1559, 1560), (10057817139820732965, 1561, 1562), (10057817139820732965, 1569, 1570), (10057817139820732965, 1587, 1588), (10057817139820732965, 1601, 1602), (10057817139820732965, 1605, 1606), (10057817139820732965, 1625, 1626), (10057817139820732965, 1628, 1629), (10057817139820732965, 1635, 1636), (10057817139820732965, 1642, 1643), (10057817139820732965, 1645, 1646), (10057817139820732965, 1651, 1652), (10057817139820732965, 1664, 1665), (10057817139820732965, 1670, 1671), (10057817139820732965, 1672, 1673), (10057817139820732965, 1684, 1685), (10057817139820732965, 1690, 1691), (10057817139820732965, 1698, 1699), (10057817139820732965, 1705, 1706), (10057817139820732965, 1708, 1709), (10057817139820732965, 1723, 1724), (10057817139820732965, 1732, 1733), (10057817139820732965, 1749, 1750), (10057817139820732965, 1754, 1755), (10057817139820732965, 1773, 1774), (10057817139820732965, 1787, 1788), (10057817139820732965, 1789, 1790), (10057817139820732965, 1800, 1801), (10057817139820732965, 1802, 1803), (10057817139820732965, 1813, 1814), (10057817139820732965, 1818, 1819), (10057817139820732965, 1822, 1823), (10057817139820732965, 1826, 1827), (10057817139820732965, 1837, 1838), (10057817139820732965, 1847, 1848), (10057817139820732965, 1850, 1851), (10057817139820732965, 1865, 1866), (10057817139820732965, 1872, 1873), (10057817139820732965, 1885, 1886), (10057817139820732965, 1889, 1890), (10057817139820732965, 1898, 1899), (10057817139820732965, 1909, 1910), (10057817139820732965, 1915, 1916), (10057817139820732965, 1920, 1921), (10057817139820732965, 1925, 1926), (10057817139820732965, 1935, 1936), (10057817139820732965, 1950, 1951), (10057817139820732965, 1957, 1958), (10057817139820732965, 1959, 1960), (10057817139820732965, 1963, 1964), (10057817139820732965, 1998, 1999), (10057817139820732965, 2005, 2006), (10057817139820732965, 2057, 2058), (10057817139820732965, 2064, 2065), (10057817139820732965, 2089, 2090), (10057817139820732965, 2102, 2103), (10057817139820732965, 2117, 2118), (10057817139820732965, 2123, 2124), (10057817139820732965, 2127, 2128), (10057817139820732965, 2129, 2130), (10057817139820732965, 2134, 2135), (10057817139820732965, 2145, 2146), (10057817139820732965, 2148, 2149), (10057817139820732965, 2151, 2152), (10057817139820732965, 2159, 2160), (10057817139820732965, 2168, 2169), (10057817139820732965, 2179, 2180), (10057817139820732965, 2181, 2182), (10057817139820732965, 2194, 2195), (10057817139820732965, 2201, 2202), (10057817139820732965, 2204, 2205), (10057817139820732965, 2214, 2215), (10057817139820732965, 2218, 2219), (10057817139820732965, 2221, 2222), (10057817139820732965, 2223, 2224), (10057817139820732965, 2239, 2240), (10057817139820732965, 2245, 2246), (10057817139820732965, 2248, 2249), (10057817139820732965, 2257, 2258), (10057817139820732965, 2266, 2267), (10057817139820732965, 2271, 2272), (10057817139820732965, 2276, 2277), (10057817139820732965, 2286, 2287), (10057817139820732965, 2290, 2291), (10057817139820732965, 2310, 2311), (10057817139820732965, 2314, 2315), (10057817139820732965, 2320, 2321), (10057817139820732965, 2323, 2324), (10057817139820732965, 2327, 2328), (10057817139820732965, 2330, 2331), (10057817139820732965, 2334, 2335), (10057817139820732965, 2339, 2340), (10057817139820732965, 2349, 2350), (10057817139820732965, 2352, 2353), (10057817139820732965, 2360, 2361), (10057817139820732965, 2371, 2372), (10057817139820732965, 2378, 2379), (10057817139820732965, 2384, 2385), (10057817139820732965, 2393, 2394), (10057817139820732965, 2394, 2395), (10057817139820732965, 2396, 2397), (10057817139820732965, 2402, 2403), (10057817139820732965, 2411, 2412), (10057817139820732965, 2423, 2424), (10057817139820732965, 2438, 2439), (10057817139820732965, 2444, 2445), (10057817139820732965, 2453, 2454), (10057817139820732965, 2458, 2459), (10057817139820732965, 2460, 2461), (10057817139820732965, 2470, 2471), (10057817139820732965, 2478, 2479), (10057817139820732965, 2484, 2485), (10057817139820732965, 2488, 2489), (10057817139820732965, 2506, 2507), (10057817139820732965, 2515, 2516), (10057817139820732965, 2519, 2520), (10057817139820732965, 2526, 2527), (10057817139820732965, 2528, 2529), (10057817139820732965, 2533, 2534), (10057817139820732965, 2540, 2541), (10057817139820732965, 2542, 2543), (10057817139820732965, 2547, 2548), (10057817139820732965, 2557, 2558), (10057817139820732965, 2566, 2567), (10057817139820732965, 2568, 2569), (10057817139820732965, 2573, 2574), (10057817139820732965, 2579, 2580), (10057817139820732965, 2593, 2594), (10057817139820732965, 2603, 2604), (10057817139820732965, 2608, 2609), (10057817139820732965, 2616, 2617), (10057817139820732965, 2619, 2620), (10057817139820732965, 2630, 2631), (10057817139820732965, 2633, 2634), (10057817139820732965, 2639, 2640), (10057817139820732965, 2646, 2647), (10057817139820732965, 2658, 2659), (10057817139820732965, 2662, 2663), (10057817139820732965, 2670, 2671), (10057817139820732965, 2680, 2681), (10057817139820732965, 2682, 2683), (10057817139820732965, 2687, 2688), (10057817139820732965, 2747, 2748), (10057817139820732965, 2762, 2763), (10057817139820732965, 2765, 2766), (10057817139820732965, 2774, 2775), (10057817139820732965, 2795, 2796), (10057817139820732965, 2802, 2803), (10057817139820732965, 2812, 2813), (10057817139820732965, 2827, 2828), (10057817139820732965, 2830, 2831), (10057817139820732965, 2840, 2841), (10057817139820732965, 2870, 2871), (10057817139820732965, 2875, 2876), (10057817139820732965, 2884, 2885), (10057817139820732965, 2893, 2894), (10057817139820732965, 2897, 2898), (10057817139820732965, 2899, 2900), (10057817139820732965, 2901, 2902), (10057817139820732965, 2903, 2904), (10057817139820732965, 2907, 2908), (10057817139820732965, 2921, 2922), (10057817139820732965, 2923, 2924), (10057817139820732965, 2929, 2930), (10057817139820732965, 2935, 2936), (10057817139820732965, 2942, 2943), (10057817139820732965, 2950, 2951), (10057817139820732965, 2952, 2953), (10057817139820732965, 2966, 2967), (10057817139820732965, 3000, 3001), (10057817139820732965, 3008, 3009), (10057817139820732965, 3031, 3032), (10057817139820732965, 3038, 3039), (10057817139820732965, 3056, 3057), (10057817139820732965, 3058, 3059), (10057817139820732965, 3065, 3066), (10057817139820732965, 3076, 3077), (10057817139820732965, 3085, 3086), (10057817139820732965, 3088, 3089), (10057817139820732965, 3090, 3091), (10057817139820732965, 3104, 3105), (10057817139820732965, 3119, 3120), (10057817139820732965, 3125, 3126), (10057817139820732965, 3127, 3128), (10057817139820732965, 3132, 3133), (10057817139820732965, 3137, 3138), (10057817139820732965, 3143, 3144), (10057817139820732965, 3149, 3150), (10057817139820732965, 3156, 3157), (10057817139820732965, 3161, 3162), (10057817139820732965, 3169, 3170), (10057817139820732965, 3180, 3181), (10057817139820732965, 3193, 3194), (10057817139820732965, 3197, 3198), (10057817139820732965, 3200, 3201), (10057817139820732965, 3207, 3208), (10057817139820732965, 3210, 3211), (10057817139820732965, 3232, 3233), (10057817139820732965, 3239, 3240), (10057817139820732965, 3244, 3245), (10057817139820732965, 3265, 3266), (10057817139820732965, 3267, 3268), (10057817139820732965, 3271, 3272), (10057817139820732965, 3279, 3280), (10057817139820732965, 3290, 3291), (10057817139820732965, 3295, 3296), (10057817139820732965, 3307, 3308), (10057817139820732965, 3313, 3314), (10057817139820732965, 3316, 3317), (10057817139820732965, 3326, 3327), (10057817139820732965, 3336, 3337), (10057817139820732965, 3340, 3341), (10057817139820732965, 3357, 3358), (10057817139820732965, 3358, 3359), (10057817139820732965, 3364, 3365), (10057817139820732965, 3366, 3367), (10057817139820732965, 3384, 3385), (10057817139820732965, 3391, 3392), (10057817139820732965, 3396, 3397), (10057817139820732965, 3401, 3402), (10057817139820732965, 3403, 3404), (10057817139820732965, 3411, 3412), (10057817139820732965, 3418, 3419), (10057817139820732965, 3421, 3422), (10057817139820732965, 3422, 3423), (10057817139820732965, 3458, 3459), (10057817139820732965, 3459, 3460), (10057817139820732965, 3465, 3466), (10057817139820732965, 3476, 3477), (10057817139820732965, 3482, 3483), (10057817139820732965, 3500, 3501), (10057817139820732965, 3506, 3507), (10057817139820732965, 3516, 3517), (10057817139820732965, 3534, 3535), (10057817139820732965, 3546, 3547), (10057817139820732965, 3569, 3570), (10057817139820732965, 3576, 3577), (10057817139820732965, 3579, 3580), (10057817139820732965, 3584, 3585), (10057817139820732965, 3586, 3587), (10057817139820732965, 3588, 3589), (10057817139820732965, 3590, 3591), (10057817139820732965, 3617, 3618), (10057817139820732965, 3631, 3632), (10057817139820732965, 3633, 3634), (10057817139820732965, 3635, 3636), (10057817139820732965, 3671, 3672), (10057817139820732965, 3677, 3678), (10057817139820732965, 3679, 3680), (10057817139820732965, 3689, 3690), (10057817139820732965, 3699, 3700), (10057817139820732965, 3703, 3704), (10057817139820732965, 3705, 3706), (10057817139820732965, 3711, 3712), (10057817139820732965, 3721, 3722), (10057817139820732965, 3726, 3727), (10057817139820732965, 3737, 3738), (10057817139820732965, 3739, 3740), (10057817139820732965, 3744, 3745), (10057817139820732965, 3761, 3762), (10057817139820732965, 3763, 3764), (10057817139820732965, 3768, 3769), (10057817139820732965, 3774, 3775), (10057817139820732965, 3781, 3782), (10057817139820732965, 3798, 3799), (10057817139820732965, 3805, 3806), (10057817139820732965, 3811, 3812), (10057817139820732965, 3825, 3826), (10057817139820732965, 3827, 3828), (10057817139820732965, 3829, 3830), (10057817139820732965, 3837, 3838), (10057817139820732965, 3843, 3844), (10057817139820732965, 3854, 3855), (10057817139820732965, 3860, 3861), (10057817139820732965, 3874, 3875), (10057817139820732965, 3884, 3885), (10057817139820732965, 3889, 3890), (10057817139820732965, 3891, 3892), (10057817139820732965, 3901, 3902), (10057817139820732965, 3904, 3905), (10057817139820732965, 3911, 3912), (10057817139820732965, 3921, 3922), (10057817139820732965, 3928, 3929), (10057817139820732965, 3936, 3937), (10057817139820732965, 3949, 3950), (10057817139820732965, 3962, 3963), (10057817139820732965, 3965, 3966), (10057817139820732965, 3985, 3986), (10057817139820732965, 3988, 3989), (10057817139820732965, 3998, 3999), (10057817139820732965, 4002, 4003), (10057817139820732965, 4016, 4017), (10057817139820732965, 4023, 4024), (10057817139820732965, 4028, 4029), (10057817139820732965, 4034, 4035), (10057817139820732965, 4040, 4041), (10057817139820732965, 4043, 4044), (10057817139820732965, 4048, 4049), (10057817139820732965, 4054, 4055), (10057817139820732965, 4062, 4063), (10057817139820732965, 4074, 4075), (10057817139820732965, 4076, 4077), (10057817139820732965, 4081, 4082), (10057817139820732965, 4093, 4094), (10057817139820732965, 4097, 4098), (10057817139820732965, 4105, 4106), (10057817139820732965, 4106, 4107), (10057817139820732965, 4119, 4120), (10057817139820732965, 4125, 4126), (10057817139820732965, 4135, 4136), (10057817139820732965, 4151, 4152), (10057817139820732965, 4169, 4170), (10057817139820732965, 4178, 4179), (10057817139820732965, 4195, 4196), (10057817139820732965, 4215, 4216), (10057817139820732965, 4229, 4230), (10057817139820732965, 4234, 4235), (10057817139820732965, 4261, 4262), (10057817139820732965, 4273, 4274), (10057817139820732965, 4280, 4281), (10057817139820732965, 4298, 4299), (10057817139820732965, 4307, 4308), (10057817139820732965, 4314, 4315), (10057817139820732965, 4318, 4319), (10057817139820732965, 4326, 4327), (10057817139820732965, 4338, 4339), (10057817139820732965, 4353, 4354), (10057817139820732965, 4366, 4367), (10057817139820732965, 4377, 4378), (10057817139820732965, 4381, 4382), (10057817139820732965, 4386, 4387), (10057817139820732965, 4391, 4392), (10057817139820732965, 4394, 4395), (10057817139820732965, 4396, 4397), (10057817139820732965, 4405, 4406), (10057817139820732965, 4411, 4412), (10057817139820732965, 4415, 4416), (10057817139820732965, 4446, 4447), (10057817139820732965, 4448, 4449), (10057817139820732965, 4460, 4461), (10057817139820732965, 4463, 4464), (10057817139820732965, 4472, 4473), (10057817139820732965, 4484, 4485), (10057817139820732965, 4494, 4495), (10057817139820732965, 4504, 4505), (10057817139820732965, 4521, 4522), (10057817139820732965, 4526, 4527), (10057817139820732965, 4547, 4548), (10057817139820732965, 4552, 4553), (10057817139820732965, 4559, 4560), (10057817139820732965, 4563, 4564), (10057817139820732965, 4568, 4569), (10057817139820732965, 4576, 4577), (10057817139820732965, 4589, 4590), (10057817139820732965, 4599, 4600), (10057817139820732965, 4607, 4608), (10057817139820732965, 4615, 4616), (10057817139820732965, 4623, 4624), (10057817139820732965, 4625, 4626), (10057817139820732965, 4655, 4656), (10057817139820732965, 4662, 4663), (10057817139820732965, 4666, 4667), (10057817139820732965, 4676, 4677), (10057817139820732965, 4685, 4686), (10057817139820732965, 4689, 4690), (10057817139820732965, 4694, 4695), (10057817139820732965, 4701, 4702), (10057817139820732965, 4720, 4721), (10057817139820732965, 4730, 4731), (10057817139820732965, 4735, 4736), (10057817139820732965, 4759, 4760), (10057817139820732965, 4769, 4770), (10057817139820732965, 4781, 4782), (1005

La herramienta **`matcher`** devuelve una lista de coincidencias. Cada coincidencia tiene tres valores:

- un identificador de la búsqueda,

- la posición inicio en la lista de tokens

- la posición final

In [15]:
# Presentamos resultados
print("La respuesta de matcher es una lista de coincidencias")
print(coincidencias)
print("\nSe han encontrado {} coincidencias con el patrón de búsqueda.".format(len(coincidencias)))

print("\nEstos son los 10 primeros patrones coincidentes encontrados (verbos):\n")
for caso in coincidencias[:10]:
    print (book_spacy[caso[1]:caso[2]])

La respuesta de matcher es una lista de coincidencias

In [16]:
# Otro ejemplo de patrón de búsqueda
# Buscamos verbos de 6 caracteres:
patron1 = [{"POS": "VERB", "LENGTH": 6}]

# Si queremos resetear el patrón de búsqueda, es importante reiniciar el matcher:
buscador = Matcher(nlp.vocab)
buscador.add("Patron1", [patron1])
coincidencias = buscador(book_spacy)

print("\nEstos son los 10 primeros patrones coincidentes encontrados (verbos de 6 caracteres):\n")
for caso in coincidencias[:10]:
    print (book_spacy[caso[1]:caso[2]])

Estos son los 10 primeros patrones coincidentes encontrados (verbos de 6 caracteres):

having
peeped
making
seemed
looked
dipped
wonder
happen
coming
looked

In [17]:
# Buscamos verbo seguido de palabra de 6 caracteres, observar diferencia con búsqueda anterior:
patron1 = [{"POS": "VERB"}, {"LENGTH": 6}]
buscador = Matcher(nlp.vocab)
buscador.add("Patron1", [patron1])
coincidencias = buscador(book_spacy)

print("\nEstos son los 10 primeros patrones coincidentes encontrados:\n")
for caso in coincidencias[:10]:
    print (book_spacy[caso[1]:caso[2]])

Estos son los 10 primeros patrones coincidentes encontrados:

flashed across
ran across
had plenty
Longitude either
get rather
answer either
noticed before
happened lately
shutting people
remembered trying

In [18]:
# Hacemos un poco más específica la búsqueda:
verbos_a_identificar = ["think"]
patron1 = [{"POS": "VERB", "LEMMA": {"IN": verbos_a_identificar}}]

buscador = Matcher(nlp.vocab)
buscador.add("Patron1", [patron1])
coincidencias = buscador(book_spacy)

print("\nSe han encontrado {} coincidencias con el patrón de búsqueda.".format(len(coincidencias)))
print("\nEstos son los 10 primeros patrones coincidentes encontrados (mostramos dos palabras antes y después)\n:")
for caso in coincidencias[:10]:
    print (book_spacy[caso[1]-2:caso[1]], "[", book_spacy[caso[1]:caso[2]] , "]", book_spacy[caso[2]:caso[2]+2])

Se han encontrado 130 coincidencias con el patrón de búsqueda.

Estos son los 10 primeros patrones coincidentes encontrados (mostramos dos palabras antes y después)
:
,' [ thought ] Alice '
did Alice [ think ] it so
when she [ thought ] it over
moment to [ think ] about stopping
!' [ thought ] Alice to
I shall [ think ] nothing of
'll all [ think ] me at
, but [ thought ] they were
Do you [ think ] you could
she'll [ think ] me for

In [19]:
# Hacemos un poco más específica la búsqueda, pidiendo que sea Alice quien hace la acción:
verbos_a_identificar = ["think"]
patron1 = [{"TEXT": "Alice"}, {"POS": "VERB", "LEMMA": {"IN": verbos_a_identificar}}]

#verbos_a_identificar = ["run"]
#patron2 = [{"POS": "VERB", "LEMMA": {"IN": verbos_a_identificar}}]

# Si queremos cambiar el patrón de búsqueda, es importante "resetear" matcher:
buscador = Matcher(nlp.vocab)
buscador.add("Patron1", [patron1])
#buscador.add("Patron2", [patron2])

coincidencias = buscador(book_spacy)

print("\nSe han encontrado {} coincidencias con el patrón de búsqueda.".format(len(coincidencias)))
print("\nEstos son los 10 primeros patrones coincidentes encontrados (mostramos dos palabras antes y después)\n:")
for caso in coincidencias[:10]:
    print (book_spacy[caso[1]-2:caso[1]], "[", book_spacy[caso[1]:caso[2]] , "]", book_spacy[caso[2]:caso[2]+2])

Se han encontrado 13 coincidencias con el patrón de búsqueda.

Estos son los 10 primeros patrones coincidentes encontrados (mostramos dos palabras antes y después)
:
nor did [ Alice think ] it so
' ( [ Alice thought ] this must
passion, [ Alice thought ] ),
.   [ Alice thought ] the whole
, and [ Alice thought ] to herself
.   [ Alice thought ] she might
and this [ Alice thought ] decidedly uncivil
, while [ Alice thought ] over all
red. [ Alice thought ] this a
began. [ Alice thought ] she had

## Ejercicio

Encontrar frases en las que Alice realiza una acción sobre un objeto.

## Solución.

In [20]:
# Añadimos otros verbos a la búsqueda:
patron1 = [{"TEXT": "Alice"}, {"POS": "VERB"}, {"POS": "DET"}, {"POS": "NOUN"}]

patron2 = [{"TEXT": "Alice"}, {"POS": "VERB"}]
# Si queremos cambiar el patrón de búsqueda, es importante "resetear" matcher:
buscador = Matcher(nlp.vocab)
buscador.add("Patron1", [patron1])
coincidencias = buscador(book_spacy)

buscador2= Matcher(nlp.vocab)
buscador2.add("Patron2", [patron2])
coincidencias2 = buscador2(book_spacy)

print("\nSe han encontrado {} coincidencias con el patrón de búsqueda.".format(len(coincidencias)))
print("\nEstos son los 10 primeros patrones coincidentes encontrados\n:")
for caso in coincidencias[:10]:
    print (book_spacy[caso[1]:caso[2]])

print("\nSe han encontrado {} coincidencias con el patrón de búsqueda.".format(len(coincidencias2)))
print("\nEstos son los 10 primeros patrones coincidentes encontrados\n:")
for caso in coincidencias2[:10]:
    print (book_spacy[caso[1]:caso[2]])

Se han encontrado 6 coincidencias con el patrón de búsqueda.

Estos son los 10 primeros patrones coincidentes encontrados
:
Alice had no idea
Alice opened the door
Alice led the way
Alice had no idea
Alice caught the baby
Alice joined the procession

Se han encontrado 113 coincidencias con el patrón de búsqueda.

Estos son los 10 primeros patrones coincidentes encontrados
:
Alice think
Alice started
Alice had
Alice had
Alice began
Alice opened
Alice ventured
Alice felt
Alice took
Alice thought

## Ejercicio

- Combine el texto de todos los libros Gutenberg disponibles en NLTK en una única cadena de texto y recorte el resultado a un millón de caracteres, sin retornos.

- Localice en los textos los números que puedan representar un año (4 dígitos).

## Solución

In [21]:
all_books = ""
ids = gutenberg.fileids()

for id in ids:
  all_books = all_books + " " + gutenberg.raw(id)

all_books = all_books.replace('\n', ' ')
all_books = all_books[0: 1000000]

print("Hemos combinado los {} libros disponibles en NLTK en una única cadena de texto de longitud {}.".format(len(ids), len(all_books)))

Hemos combinado los 18 libros disponibles en NLTK en una única cadena de texto de longitud 1000000.

In [22]:
all_books_spacy = nlp(all_books)
patron1 = [{"IS_DIGIT": True, "LENGTH": 4}]

buscador = Matcher(nlp.vocab)
buscador.add("Patron1", [patron1])
coincidencias = buscador(all_books_spacy)

print("\nSe han encontrado {} coincidencias con el patrón de búsqueda.".format(len(coincidencias)))
print("\nEstos son los 10 primeros patrones coincidentes encontrados (mostramos dos palabras antes y después)\n:")
for caso in coincidencias[:10]:
    print (all_books_spacy[caso[1]-2:caso[2]+2])

Se han encontrado 12 coincidencias con el patrón de búsqueda.

Estos son los 10 primeros patrones coincidentes encontrados (mostramos dos palabras antes y después)
:
Jane Austen 1816]
Jane Austen 1818]
1, 1760, married
15, 1784, Elizabeth
who died 1800) he
1, 1785; Anne
9, 1787; a
5, 1789; Mary
20, 1791."
16, 1810, Charles

In [23]:
print("\nSe han encontrado {} coincidencias con el patrón de búsqueda.".format(len(coincidencias)))
print("\nEstos son los 10 primeros patrones coincidentes encontrados (supuestamente años):\n")
for caso in coincidencias[:10]:
    print (all_books_spacy[caso[1]:caso[2]])

Se han encontrado 12 coincidencias con el patrón de búsqueda.

Estos son los 10 primeros patrones coincidentes encontrados (supuestamente años):

1816
1818
1760
1784
1800
1785
1787
1789
1791
1810

# 4 - Reconocimiento de entidades (Name entity recognition NER)

Si bien **POS tagging** nos indicará que palabras como `Janet`, `Stanford University` o `Colorado` son **nombres propios**, estos nombres propios se refieren a **tipos de entidades distintas**: `Janet` es una **persona**, `Stanford University` es una **organización** y `Colorado` es una **entidad geopolítica**.

La tarea de **reconocimiento de entidades (ing. "Name Entity Recognition", NER)** consiste tanto en encontrar tramos de texto que constituyan **nombres propios** como etiquetar el **tipo de entidad**. Las cuatro etiquetas de entidad son las más comunes: **PER (persona)**, **LOC (ubicación)**, **ORG (organización)** o **GPE (entidad geopolítica)**. Sin embargo, el término entidad se extiende comúnmente para incluir cosas que no son entidades per se, incluidas fechas, horas y otros tipos de expresiones temporales, e incluso expresiones numéricas como precios.

Los distintos modelos NER son fundamentalmente **algoritmos de aprendizaje automático entrenados sobre bases de datos etiquetadas**. Por tanto, su rendimiento está ligado al tipo de texto en que fueron entrenados y esto implica que para un nuevo texto pueden no alcanzar las mismas prestaciones.  Si se considera necesario, [Spacy permite hacer un ajuste fino](https://course.spacy.io/en/chapter4) (reentrenar) cualquiera de sus modelos a un nuevo corpus de documentos.

## 4.1 - NER en Spacy

**Spacy** implementa alguno de los **algoritmos más avanzados del estado del arte para NER**.

<img src="http://www.tsc.uc3m.es/~navia/figures/spacy_NER.png" width="70%">

**Nota**: estas prestaciones se refieren a una versión especifica de Spacy (2025), se aconseja siempre revisr las prestaciones de las versiones más recientes.

In [24]:
text = """Three more countries have joined an "international grand committee" of parliaments, adding to calls for Facebook’s boss, Mark Zuckerberg, to give evidence on misinformation to the coalition. Brazil, Latvia and Singapore bring the total to eight different parliaments across the world, with plans to send representatives to London on 27 November with the intention of hearing from Zuckerberg. Since the Cambridge Analytica scandal broke, the Facebook chief has only appeared in front of two legislatures: the American Senate and House of Representatives, and the European parliament. Facebook has consistently rebuffed attempts from others, including the UK and Canadian parliaments, to hear from Zuckerberg. He added that an article in the New York Times on Thursday, in which the paper alleged a pattern of behaviour from Facebook to "delay, deny and deflect" negative news stories, "raises further questions about how recent data breaches were allegedly dealt with within Facebook."""
print(text)

Three more countries have joined an "international grand committee" of parliaments, adding to calls for Facebook’s boss, Mark Zuckerberg, to give evidence on misinformation to the coalition. Brazil, Latvia and Singapore bring the total to eight different parliaments across the world, with plans to send representatives to London on 27 November with the intention of hearing from Zuckerberg. Since the Cambridge Analytica scandal broke, the Facebook chief has only appeared in front of two legislatures: the American Senate and House of Representatives, and the European parliament. Facebook has consistently rebuffed attempts from others, including the UK and Canadian parliaments, to hear from Zuckerberg. He added that an article in the New York Times on Thursday, in which the paper alleged a pattern of behaviour from Facebook to "delay, deny and deflect" negative news stories, "raises further questions about how recent data breaches were allegedly dealt with within Facebook.

In [25]:
import sys
!{sys.executable} -m pip install spacy spacy-transformers
!{sys.executable} -m spacy download en_core_web_trf
!{sys.executable} -m spacy download en_core_web_lg

zsh:1: no such file or directory: /Users/matveypro/Desktop/MyKnowledge/04
zsh:1: no such file or directory: /Users/matveypro/Desktop/MyKnowledge/04
zsh:1: no such file or directory: /Users/matveypro/Desktop/MyKnowledge/04

In [29]:
# =======================================================
# en_core_web_trf requiere instalar una librería de tranformers...
# =======================================================
#!pip install spacy
#!pip install spacy-transformers
#import spacy_transformers
#!python -m spacy download en_core_web_trf

# Como segunda mejor alternativa tenemos
!python -m spacy download en_core_web_lg

Collecting en-core-web-lg==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_lg-3.8.0/en_core_web_lg-3.8.0-py3-none-any.whl (400.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 400.7/400.7 MB 17.3 MB/s  0:00:22:00:0100:01
Installing collected packages: en-core-web-lg
Successfully installed en-core-web-lg-3.8.0
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_lg')

In [30]:
#nlp = spacy.load('en_core_web_trf')
nlp = spacy.load('en_core_web_lg')

Una vez cargado el modelo y procesado nuestro texto, podemos acceder a la **etiqueta asociada al tipo de entidad**, algunas etiquetas comunes son:

- **PERSON**:      People, including fictional.
- **ORG**:         Companies, agencies, institutions, etc.
- **GPE**:         Countries, cities, states (Geopolitical entities).
- **LOC**:         Non-GPE locations, mountain ranges, bodies of water.
- **DATE**:        Absolute or relative dates or periods.
- **ORDINAL**:     “first”, “second”, etc.
- **CARDINAL**:    Numerals that do not fall under another type.

En el siguiente ejercicio revisaremos la **lista completa de etiquetas** disponibles.

### Ejercicio:

Dada la siguiente lista extendida de etiquetas NER, construir una tabla "pandas" con la etiqueta y su descripción ("spacy.explain()").

### Solución:

In [31]:
list_of_tags = ["CARDINAL", "DATE", "EVENT", "FAC", "GPE", "LANGUAGE", "LAW", "LOC", "MONEY", "NORP", "ORDINAL", "ORG", "PERCENT", "PERSON", "PRODUCT", "QUANTITY", "TIME", "WORK_OF_ART", "LOC", "MISC", "ORG", "PER"]

data = [ [tag, spacy.explain(tag)] for tag in list_of_tags]

df = pd.DataFrame(data, columns=['Etiqueta NER','Descripción'])
df.style.set_properties(**{'text-align': 'left'})

Analicemos el texto anterior para ver sus etiquetas NER:

In [32]:
text_spacy = nlp(text)

ner_tagged = [(word.text, word.ent_type_) for word in text_spacy]
# Imprimimos las palabras con TAG:

NER_texto = []
for token in ner_tagged:
  if token[1] != '':
    NER_texto.append((token[0], token[1]))

df = pd.DataFrame(NER_texto, columns=['Palabra', 'Etiqueta NER'])
df.style.set_properties(**{'text-align': 'left'})

El paquete `displacy` de spaCy proporciona una **interfaz visual** muy útil en este caso:

In [33]:
from spacy import displacy

displacy.render(text_spacy, style='ent', jupyter=True)

### Ejercicio

En la cadena de texto conteniendo todos los libros de NLTK, **localice la lista de todos los personajes mencionados**. Muestre la lista resultante sin repeticiones de nombres y ordenada alfabéticamente.

**Nota**: si el procesado se demora demasiado tiempo, se puede recortar la cadena a un número más reducido de caracteres, al menos para las pruebas de desarrollo. En una cadena de longitud 5000 caracteres ya aparecen varios nombres.

### Solución:

In [34]:
from spacy.matcher import Matcher
#all_books_spacy = nlp(all_books)
parte_books = all_books[0:5000]
books_spacy = nlp(parte_books)

patron1 = [{"ENT_TYPE": "PERSON"}]

buscador = Matcher(nlp.vocab)
buscador.add("Patron1", [patron1])
coincidencias = buscador(books_spacy)

names = []
for caso in coincidencias:
    names.append(all_books_spacy[caso[1]:caso[2]].text)

names = list(set(names))
names.sort()

print("\nEsta es la lista de personajes, en orden alfabético\n:")
for name in names:
  print(name)

Esta es la lista de personajes, en orden alfabético
:
Austen
Emma
Isabella
Jane
Taylor
Weston
Woodhouse
Woodhouses

Al final del tema propondremos un ejercicio de ampliación para mejorar estos resultados.

# 5 - Dependency parsing

**Dependency parsing** es el proceso de extraer el **análisis sintáctico de dependencias de una oración** para representar su **estructura gramatical**. Define la relación de dependencia entre las palabras clave y sus dependientes:

- El **encabezado** de una frase no tiene dependencia y se llama raíz (**ROOT**). Suele ser un verbo.
- El **resto de palabras** están **vinculadas al encabezado**.

Este análisis proporciona información sobre **qué papel juega una palabra en el texto y cómo se relacionan las diferentes palabras entre sí**. También se utiliza en el *shallow parsing* y en NER.

Las dependencias se codifican en una **estructura de tipo árbol**: las palabras son los nodos que están conectadas en función de su dependencia gramatical.

In [35]:
sentence = 'I read a book'
doc_spacy = nlp(sentence)
NER_data = []
for token in doc_spacy:
  NER_data.append((token.text, token.tag_, token.head.text, token.dep_))

df = pd.DataFrame(NER_data, columns=['Palabra', 'POS TAG', 'HEAD', 'DEP'])
df.style.set_properties(**{'text-align': 'left'})
display(df)

  Palabra POS TAG  HEAD    DEP
0       I     PRP  read  nsubj
1    read     VBD  read   ROOT
2       a      DT  book    det
3    book      NN  read   dobj

En el ejemplo anterior, podemos ver **distintos tipos de relaciones entre las palabras**. Una lista completa puede consultarse en este enlace sobre [**Stanford typed dependencies**](https://nlp.stanford.edu/software/dependencies_manual.pdf). Las más habituales son:

- **Sujeto**, nsubj (nominal subject): El sujeto de la oración.

- **Objeto directo**, dobj (direct object): El objeto directo sobre el que recae la acción.

- **Objeto indirecto**, iobj (indirect object): El objeto indirecto.

- **Modificadores de Sustantivos**: amod (adjectival modifier), det (determiner), nmod (nominal modifier)

- **Modificadores de Verbos y Adverbios**: advmod (adverbial modifier), aux (auxiliary verb)

- **Relaciones de Estructura y Otros**, root (root): La palabra principal de la oración (usualmente el verbo principal), cc (coordinating conjunction), conj (conjunct), punct (punctuation).

## 5.1 - Visualización de interdependencias con Spacy.

Esta **interdependencia entre palabras** se observa mejor con un **grafo**. Spacy nos proporciona herramientas de visualización:

In [36]:
print(sentence)

displacy.render(doc_spacy, style="dep")

I read a book

Veamos otro ejemplo un poco más complejo:

In [37]:
sentence = 'The hungry bear has eaten all the berries in the field'
doc_spacy = nlp(sentence)

NER_data = []
for token in doc_spacy:
  NER_data.append((token.text, token.tag_, token.head.text, token.dep_))

df = pd.DataFrame(NER_data, columns=['Palabra', 'POS TAG', 'HEAD', 'DEP'])
df.style.set_properties(**{'text-align': 'left'})
display(df)

    Palabra POS TAG     HEAD     DEP
0       The      DT     bear     det
1    hungry      JJ     bear    amod
2      bear      NN    eaten   nsubj
3       has     VBZ    eaten     aux
4     eaten     VBN    eaten    ROOT
5       all     PDT  berries  predet
6       the      DT  berries     det
7   berries     NNS    eaten    dobj
8        in      IN  berries    prep
9       the      DT    field     det
10    field      NN       in    pobj

In [38]:
print(sentence)

# We adjust visualization to obtain a more compact graph:
options = {
    "distance": 90,    # Default is usually around 175
    "compact": False,   # Makes arcs flatter and squared if True
    "color": "#444",   # Optional: color of text/arcs
    "bg": "#ffffff",   # Optional: background color
    "font": "Source Sans Pro"
}

# Render with the options
displacy.render(doc_spacy, style="dep", options=options)

The hungry bear has eaten all the berries in the field


SpaCy proporciona atributos tales como `children`, `lefts`, `rights`, and `subtree` para recorrer el árbol de dependencias. Veamos cómo se aplicaría en una frase:

Vemos que la raíz de la frase (**ROOT**) es el token 4 (verbo "eaten"). Sus dependencias directas (`children`) serían:

In [39]:
print(list(doc_spacy[4].children))

[bear, has, berries]

Y podemos identificar el papel de cada una de ellas en la oración:

In [40]:
for token in doc_spacy[4].children:
  print(token.text, token.dep_, token.tag_)

bear nsubj NN
has aux VBZ
berries dobj NNS

Las dependencias de la palabra  "**bear**" serían:

In [41]:
print(list(doc_spacy[2].children))

[The, hungry]

In [42]:
for token in doc_spacy[2].children:
  print(token.text, token.dep_, token.tag_)

The det DT
hungry amod JJ

También podemos analizar las dependencias a izquierda y derecha:

In [43]:
print("Dependencias a la izquierda de la palabra 'eaten':")
print(list(doc_spacy[4].lefts))

print("\nDependencias a la izquierda de la palabra 'bear':")
print(list(doc_spacy[2].lefts))

Dependencias a la izquierda de la palabra 'eaten':
[bear, has]

Dependencias a la izquierda de la palabra 'bear':
[The, hungry]

In [44]:
print("Dependencias a la derecha de la palabra 'eaten':")
print(list(doc_spacy[4].rights))

print("\nDependencias a la derecha de la palabra 'bear':")
print(list(doc_spacy[2].rights))

Dependencias a la derecha de la palabra 'eaten':
[berries]

Dependencias a la derecha de la palabra 'bear':
[]

El comando ``subtree`` nos permite aislar las palabras que dependen directamente de una dada:

In [45]:
print("Las palabras dependientes de {} son:".format(doc_spacy[4].text))
print(list(doc_spacy[4].subtree))

print("\nLas palabras dependientes de {} son:".format(doc_spacy[2].text))
print(list(doc_spacy[2].subtree))

print("\nLas palabras dependientes de {} son:".format(doc_spacy[7].text))
print(list(doc_spacy[7].subtree))

Las palabras dependientes de eaten son:
[The, hungry, bear, has, eaten, all, the, berries, in, the, field]

Las palabras dependientes de bear son:
[The, hungry, bear]

Las palabras dependientes de berries son:
[all, the, berries, in, the, field]

# 6 Ejercicios de ampliación

## Ejercicio:

Realice un **postprocesado de los nombres propios identificados**:

- comprobación de los nombres compuestos. Por ejemplo, en la lista debería aparecer "Jane Austen", pero no "Jane" o "Austen"
- eliminación de nombres con signos de puntuación
- eliminación de nombres que no comienzan con una mayúscula
- etc.

## Solución:

In [46]:
from spacy.matcher import Matcher
#all_books_spacy = nlp(all_books)
parte_books = all_books[0:150000]
books_spacy = nlp(parte_books)

patron1 = [{"ENT_TYPE": "PERSON"}]
patron2 = [{"ENT_TYPE": "PERSON"}, {"ENT_TYPE": "PERSON"}]
patron3 = [{"ENT_TYPE": "PERSON"}, {"ENT_TYPE": "PERSON"}, {"ENT_TYPE": "PERSON"}]

buscador = Matcher(nlp.vocab)
buscador.add("Patron1", [patron1])
buscador.add("Patron2", [patron2])
buscador.add("Patron3", [patron3])
coincidencias = buscador(books_spacy)

names = []
for caso in coincidencias:
    names.append(all_books_spacy[caso[1]:caso[2]].text)

names_L1 = [name for name in names if len(name.split()) == 1]
names_L2 = [name for name in names if len(name.split()) == 2]
names_L3 = [name for name in names if len(name.split()) == 3]

# Filtramos los nonbres sencillos que aparecen en los dobles
nombres_multiples = " ".join(names_L2) + " " + " ".join(names_L3)

names_L1_filtrados = [name for name in names_L1 if name not in nombres_multiples]

names = names_L1_filtrados + names_L2 + names_L3

names = list(set(names))

# Filtramos los nombres:

names_OK = []
names_deleted = []

for name in names:
  remove = False
  for token in nlp(name):
    if not token.is_alpha:
      remove = True
    if token.is_punct:
      remove = True
    if token.text.lower() == token.text:
      remove = True

  if not remove:
    names_OK.append(name)
  else:
    names_deleted.append(name)

names_OK.sort()

print("\nEsta es la lista de personajes filtrada, en orden alfabético:\n")
for name in names_OK:
  print(name)

print("\nEsta es la lista de nombres eliminados:\n")
for name in names_deleted:
  print(name)

Esta es la lista de personajes filtrada, en orden alfabético:

Bella
Catherine
Cole
Dear Harriet
Donwell Abbey
Elizabeth
Elton
Eltons
Emma Woodhouse
Enscombe
Farmer Mitchell
Frank Churchill
Garrick
George
Goddard
Hannah
Harriet Smith
Henry
Highbury
Isabella
James
Jane Austen
John Knightley
Martins
Miss Bates
Miss Prince
Miss Richardson
Miss Smith
Miss Smiths
Miss Woodhouse
Nash
Perry
Robert Martin
Shakespeare
Taylor
Welch
Weston
Woodhouses

Esta es la lista de nombres eliminados:

My dear Harriet
a Robert Martin
answer!--you
a Robert
Harriet Smith's
dear Harriet
quarter:--Robert Martin
Miss Woodhouse"--he
satisfied--
thought!--she
you,"--said
Knightley.--"Robert Martin
John Knightley's
a Harriet Smith
My dear
loves Emma
John loves Emma
John loves
a Harriet
Robert Martin's
Miss Smith's
Farmer Mitchell's
Elton--

## Ejercicio

Procesar de nuevo los libros frase a frase:

- identifique las frases en que la palabra raíz (ROOT) es un verbo.
- Visualize algunos de los grafos de dependencias de las frase en dichos casos
- identifique el sujeto de cada acción y muestre los pares (sujeto, verbo)
- Muestre las primeras frases que cumplen dicho criterio (sin mostrar los grafos de dependencias).

## Solución:

In [47]:
parte_books = all_books[0:4000]
books_spacy = nlp(parte_books)

for frase in books_spacy.sents:
  verbo_root = False
  for token in frase:
    #print(token.text, token.pos_, token.dep_)
    if token.pos_ == "VERB" and token.dep_ == "ROOT":
      verbo = token.text
      verbo_root = True
      sujeto = ""
      for tt in token.lefts:
        if tt.dep_ == "nsubj":
          sujeto = tt.text
      print(sujeto, "--->", verbo)

  #if verbo_root:
  #  displacy.render(frase, style="dep")

Woodhouse ---> seemed
mother ---> died
years ---> had
they ---> living
Sorrow ---> came
 ---> left
father ---> composed
event ---> had
 ---> felt
She ---> recalled
debt ---> owing
She ---> loved
He ---> meet